Create deputados page
Rickecr/CamaraDosDeputados pull request #85
Opened 2020-10-22 15:10 UTC by tuliocll

#77 

**Descrição do bug/feature:**
Criar tela de listagem dos deputados

**Solução**
Criar novos componentes; Card de deputado, tag, paginação, loading e pesquisa.

**Coisas a fazer**
Nada

2020-10-23 11:57 UTC, richecr commented
Olá @tuliocll, eu baixei suas alterações aqui e executei, mas achei um problema na paginação das despesas, quando eu clico para passar para a próxima, nada acontece, ele não atualiza a página, pelo que vi ele não está fazendo a requisição a API.

Também está com um erro no build(o log não dá muitos detalhes, mas vou mandar um print abaixo do erro), antes do seu último commit estava com esse erro nos arquivos `scss` que importavam o componente `Header`(foi alterado recentemente) e os seus arquivos estavam apontando para o `Main`(nome antigo do componente), mas vi que você alterou os arquivos já. Mas acho que o erro ainda está nesses arquivos.

![build_erro](https://user-images.githubusercontent.com/25726888/97000846-b9268680-150d-11eb-9044-12ed8a43e7fb.png)

2020-10-23 11:57 UTC, richecr requested changes

2020-10-23 11:57 UTC, richecr commented on src/components/DeputadoCard/styles.scss
> +@import '../Header/variables.scss';
Estou achando que isso que está causando o erro do build, foi a única coisa que percebi que vi que mudou da versão anterior. Usar os `//variables.scss`  no lugar de `/variables.scss`.

2020-10-23 11:57 UTC, richecr commented on src/components/Pagination/styles.scss
> +@import '../Header/variables.scss';
Mesmo caso aqui.

2020-10-23 12:18 UTC, richecr requested changes

2020-10-23 12:18 UTC, richecr commented on src/pages/Deputados/index.js
> +  const [searchTerm, setSearchTerm] = useState('silva');
Aqui ele já está fazendo uma filtragem por `silva`.

2020-10-23 12:48 UTC, tuliocll commented on src/components/DeputadoCard/styles.scss
> +@import '../Header/variables.scss';
O erro no build esta sendo por causa das variáveis declaradas e não usadas, o netlify tem um recurso que erros de lint não deixa gerar o build e lançar em prod. Vou remover as variáveis não usadas (foram as que eu deixei pra futuras implementações)

2020-10-23 12:48 UTC, tuliocll commented on src/pages/Deputados/index.js
> +  const [searchTerm, setSearchTerm] = useState('silva');
Acho que coloquei pra algum teste, vou remover também

2020-10-23 12:52 UTC, tuliocll commented
Acabei de fazer outro commit, deve corrigir

2020-10-23 12:55 UTC, tuliocll commented
> Olá @tuliocll, eu baixei suas alterações aqui e executei, mas achei um problema na paginação das despesas, quando eu clico para passar para a próxima, nada acontece, ele não atualiza a página, pelo que vi ele não está fazendo a requisição a API.
> 
> Também está com um erro no build(o log não dá muitos detalhes, mas vou mandar um print abaixo do erro), antes do seu último commit estava com esse erro nos arquivos `scss` que importavam o componente `Header`(foi alterado recentemente) e os seus arquivos estavam apontando para o `Main`(nome antigo do componente), mas vi que você alterou os arquivos já. Mas acho que o erro ainda está nesses arquivos.
> 
> ![build_erro](https://user-images.githubusercontent.com/25726888/97000846-b9268680-150d-11eb-9044-12ed8a43e7fb.png)

Essa parte da paginação nas despesas foi por que eu remodelei o componente de paginação e não adaptei ele na tela das despesas, eu comentei no issue #75 , não quis mexer pra não atrapalhar quem pegou essa task.

2020-10-25 03:19 UTC, richecr commented
Pronto, desculpa pela demora em analisar as alterações. Acho que está tudo correto agora. Vou aceitar e comentar na issue #75.

2020-10-25 03:19 UTC, merged